version: "3.9"
   
services:
  web:
    build: .
    command: uvicorn chemondis.asgi:application --host 0.0.0.0
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY
      - APP_ID
